import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import TopNav from "@/components/navbar/TopNav";

// 定义网站的元数据配置
export const metadata: Metadata = {
  title: "Cupid-Web", // 网站标题
  description: "Generated by create next app", // 网站描述
};

/**
 * 根布局组件
 * 这是整个应用的最外层布局组件，所有页面都将在此布局中渲染
 * 
 * @param {Object} props - 组件属性
 * @param {React.ReactNode} props.children - 子组件，将被渲染在布局中
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopNav /> {/* 顶部导航栏组件 */}
        <Providers>{children}</Providers> {/* NextUI提供者包裹的内容区域 */}
      </body>
    </html>
  );
}
